version: '3.1'
services:
  interface:
    container_name: interface
    build: ./ex2
    restart: always
    environment:
      - API_URL=http://data_api:7001
      - PORT=7000
    ports:
      - "15031:7000"
    networks:
      - teste_net

  data_api:
    container_name: data_api
    build: ./ex1
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/plantas
      - PORT=7001
    ports:
      - "15030:7001"
    depends_on:
      - mongodb
    networks:
      - teste_net

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "13002:27017"
    networks:
      - teste_net
    volumes:
      - mongodata:/data/db
      - ./datasets:/datasets
networks:
  teste_net:
    driver: bridge

volumes:
  mongodata:
    driver: local